### PR TITLE
Update PIXI method to use PIXI v5

### PR DESCRIPTION
**Pull request by haochang**
Hello there are a lot api changes when migrating PIXI from V4 to V5. 

Could you check the PR please to update the library work with PIXI v5? As my company is recently upgrade to use V5 PIXI and we also want to keep using your library for playing GIFs in the canvas.

Thanks so much.

### CODE REVIEW

**Comment by sbfkcel** [comment]
Tested code currently supports pixi v5 +

**Comment by haochang** [comment]
Hi,  `PIXI.BaseTexture.fromCanvas ()` is deprecated since 5.0.0
But the current code is still using it

https://raw.githubusercontent.com/sbfkcel/pixi-apngAndGif/master/dev/PixiApngAndGif.js

Also `PIXI.ticker.Ticker.` is `PIXI.Ticker()` now https://pixijs.download/v5.0.0/docs/PIXI.Ticker.html

Could you double check please?

**Comment by haochang** [comment]
Can this be reopen please?

I didn't put the changes to `dist` as no idea how it's be complied but please check the diffs. There are a few breaking changes when migrating PIXI from V4 to V5.

**Comment by sbfkcel** [comment]
Thanks for the reminder. I have updated and submitted. Use the latest version to eliminate pixi5.0 warnings.

**Comment by haochang** [comment]
Thank you very much!
非常感谢！

**Comment by sbfkcel** [comment]
中国人讲什么英语。

**Comment by haochang** [comment]
This is a public place.
I'd like to speak to you privately in Chinese but other people on the similar issue regarding to the library would like to know what's going on.

**Pull request closed without merging**
